repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0
    hooks:
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
        exclude: ^tests/testing.py$
    -   id: flake8
    -   id: requirements-txt-fixer
-   repo: git://github.com/asottile/reorder_python_imports
    rev: v1.1.0
    hooks:
    -   id: reorder-python-imports
