-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 616c1ebd1898c91de9a0548866a59cbd9f4547f6
    hooks:
    -   id: check-added-large-files
        language_version: python2.7
    -   id: check-merge-conflict
        language_version: python2.7
    -   id: trailing-whitespace
        language_version: python2.7
    -   id: end-of-file-fixer
        language_version: python2.7
    -   id: autopep8-wrapper
        language_version: python2.7
    -   id: check-yaml
        language_version: python2.7
    -   id: debug-statements
        language_version: python2.7
    -   id: name-tests-test
        language_version: python2.7
    -   id: flake8
        language_version: python2.7
    -   id: requirements-txt-fixer
        language_version: python2.7
