language: python
matrix:
  include: # These should match the tox env list
    -  env: TOXENV=py27
       python: 2.7
    -  env: TOXENV=py36
       python: 3.6
    -  env: TOXENV=pre-commit
       python: 3.6
install: pip install coveralls tox
script: tox
# Special snowflake.  Our tests depend on a credentials_secret.json
before_install:
    - cp tests/json/credentials.json tests/json/credentials_secret.json
after_success:
    - coveralls
cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/.pre-commit
